apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: rbillon59/jmeter-k8s-base:5.4.1
        imagePullPolicy: Always
        env:
        - name: MODE
          value: "MASTER"
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && while true; do sleep 30;done"]
        ports:
        - containerPort: 60000
        resources:
          requests:
            memory: "1024Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "256m"
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/jmeter/apache-jmeter/bin/jmeter
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Never