apiVersion: batch/v1
kind: Job
metadata:
  name: jmeter-master
  labels:
    jmeter_mode: master
spec:
  completions: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: rbillon59/jmeter-k8s-base:5.4.1
        imagePullPolicy: Always
        volumeMounts:
            - mountPath: /report
              name: jmeter-data-dir
        env:
        - name: MODE
          value: "MASTER"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/bash"]
        args: ["-c", "trap 'exit 0' SIGUSR1 && while true; do sleep 30;done"]
        ports:
        - containerPort: 60000
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1024m"
          limits:
            memory: "2048Mi"
            cpu: "1024m"
        livenessProbe:
          exec:
            command:
            - cat
            - /opt/jmeter/apache-jmeter/bin/jmeter
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Never
      volumes:
        - name: jmeter-data-dir
          persistentVolumeClaim:
            claimName: jmeter-data-dir-pvc